# This workflow will build a .NET project 

# Test workflow
# Test workflow #2
# Test workflow #3

name: Build, Test and Publish (PreMerge_Validation)

# name for the workflow run, using the commit SHA to identify the specific commit triggering the workflow.
run-name: "commit: ${{ github.sha }}" 

on:
  # The workflow will run whenever a `push` event occurs on the `feature/*` branch.  
  push:
    branches: [ "feature/*" ]
    # The workflow will also run whenever a `pull_request` event targets the `main` branch.  
  pull_request:
    branches: [ "main" ]

permissions:
  # Grants access to the repo contents and to checkout this repo
  contents: write

defaults:
  run:
    # Set the default shell to PowerShell for all run steps in the workflow.
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Replace Nuget_CustomFeedPassword
      run: |
        sed -i 's|%Nuget_CustomFeedPassword%|${{ secrets.AZURE_DEVOPS_PAT }}|g' src/CLUK.Skeleton.API/NuGet.Config

    - name: Restore Packages
      run: dotnet restore src/CLUK.Skeleton.API/CLUK.Skeleton.API.csproj --configfile src/CLUK.Skeleton.API/NuGet.Config

    - name: Execute Discovered Test Projects
      run: dotnet test src/CLUK.Skeleton.API.Tests/CLUK.Skeleton.API.Tests.csproj

    - name: Publish
      run: dotnet publish src/CLUK.Skeleton.API/CLUK.Skeleton.API.csproj --configuration Release --output ./publish
      
