# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and Publish (PreMerge_Validation)

run-name: "commit: ${{ github.sha }}" # name for the workflow run, using the commit SHA to identify the specific commit triggering the workflow.

on:
  push:
    branches: [ "feature/*" ] # The workflow will run whenever a `push` event occurs on the `feature/*` branch.  
  pull_request:
    branches: [ "main" ] # The workflow will also run whenever a `pull_request` event targets the `main` branch.  

permissions:
  contents: write # grants access to the repo contents and to checkout this repo

defaults:
  run:
    shell: pwsh # Set the default shell to PowerShell for all run steps in the workflow.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Replace Nuget_CustomFeedPassword
      run: |
        sed -i 's|%Nuget_CustomFeedPassword%|${{ secrets.AZURE_DEVOPS_PAT }}|g' src/CLUK.Skeleton.API/NuGet.Config

    - name: Restore Packages
      run: dotnet restore src/CLUK.Skeleton.API/CLUK.Skeleton.API.csproj --configfile src/CLUK.Skeleton.API/NuGet.Config

#    # tests not working.
#    - name: Execute Discovered Test Projects
#      run: dotnet test src/CLUK.Skeleton.API.Tests/CLUK.Skeleton.API.Tests.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/CLUK.Skeleton.API/CLUK.Skeleton.API.csproj --configuration Release --output ./publish

    - name: Debug API Call
      shell: pwsh
      run: |
        Write-Host "Triggering CodeQL Workflow..."
        $headers = @{
          Authorization = "Bearer ${{ secrets.WORKFLOW_TRIGGER_PAT }}"
          Accept = "application/vnd.github.v3+json"
        }
        $body = @{
          ref = "main"
        } | ConvertTo-Json -Depth 10
        Write-Host "Headers: $($headers | Out-String)"
        Write-Host "Body: $($body | Out-String)"
        Write-Host "URL: https://api.github.com/repos/CanadaLifeUK/gha.test/actions/workflows/codeql.yml/dispatches"
        Invoke-RestMethod -Uri "https://api.github.com/repos/CanadaLifeUK/gha.test/actions/workflows/codeql.yml/dispatches" -Method Post -Headers $headers -Body $body

    - name: Trigger CodeQL Workflow
      shell: pwsh
      run: |
        $headers = @{
          Authorization = "Bearer ${{ secrets.WORKFLOW_TRIGGER_PAT }}"
          Accept = "application/vnd.github.v3+json"
        }
        $body = @{
          ref = "main"
        } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "https://api.github.com/repos/CanadaLifeUK/gha.test/actions/workflows/codeql.yml/dispatches" -Method Post -Headers $headers -Body $body
        
#    - name: Trigger CodeQL Workflow
#      run: |
#        curl -X POST \
#          -H "Authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_PAT }}" \
#          -H "Accept: application/vnd.github.v3+json" \
#          https://api.github.com/repos/CanadaLifeUK/gha.test/actions/workflows/codeql.yml/dispatches \
#          -d '{"ref":"main"}' 
