name: Dependabot Updates

on:
  workflow_dispatch: # Allows manual triggering of Dependabot updates
  workflow_run: # Triggers after another workflow completes
    workflows: ["CodeQL (PreMerge_Validation)"] # Name of the workflow to depend on
    types:
      - completed # Trigger only when the dependent workflow completes successfully

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Trigger Dependabot
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update dependencies via Dependabot"
        branch: dependabot-updates
