# This workflow will perform the quality checks

name: Quality Checks


run-name: "commit: ${{ github.sha }}" # name for the workflow run, using the commit SHA to identify the specific commit triggering the workflow.

on:
  push:
    branches: [ "feature/*" ] # The workflow will run whenever a `push` event occurs on the `feature/*` branch.  
  pull_request:
    branches: [ "main" ] # The workflow will also run whenever a `pull_request` event targets the `main` branch.  
